name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run lint
        run: npm run lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Run tests
        run: npm test
